#!/bin/bash
# Manual Testing Guide for Sistem Pengumpulan Laporan Praktikum
# Run this script and follow on-screen instructions

echo "========================================"
echo "PANDUAN TESTING SISTEM PENGUMPULAN LAPORAN PRAKTIKUM"
echo "========================================"
echo ""
echo "Database credentials:"
echo "  User: pbo_user"
echo "  Password: Pbo!Praktikum2026"
echo "  Database: db_laporan_praktikum"
echo ""
echo "Available users for testing:"
echo "  - Mahasiswa: mhs1 / 12345 (Dapot Matthew, NIM 231001001)"
echo "  - Mahasiswa: mhs2 / 12345 (Andi Pratama, NIM 231001002)"
echo "  - Dosen/Asisten: asisten1 / 12345 (Rina Asisten)"
echo "  - Dosen/Asisten: asisten2 / 12345 (Budi Asisten)"
echo ""
echo "========================================"
echo "Workflow to Test:"
echo "========================================"
echo "1. Login sebagai asisten1 (Dosen)"
echo "   - Pilih Menu 1: Buat Jadwal Praktikum"
echo "   - Input materi: 'Sorting Implementation'"
echo "   - Input tanggal praktikum: '2025-01-15'"
echo "   - Sistem auto-set batas akhir: '2025-01-18' (3 hari kemudian)"
echo ""
echo "2. Login sebagai mhs1 (Mahasiswa)"
echo "   - Pilih Menu 1: Lihat Jadwal Praktikum & Tenggat"
echo "   - Lihat jadwal yang telah dibuat asisten1"
echo "   - Pilih Menu 2: Kumpulkan Laporan Praktikum"
echo "   - Pilih jadwal ID dari step sebelumnya"
echo "   - Input judul & hasil praktikum"
echo "   - Sistem auto-set tanggal kumpul ke hari ini"
echo "   - Sistem auto-check: Apakah tepat waktu atau terlambat"
echo ""
echo "3. Login sebagai asisten1 (Dosen)"
echo "   - Pilih Menu 2: Cek Laporan Masuk"
echo "   - Lihat laporan dari mhs1 (status: TEPAT_WAKTU)"
echo "   - Pilih Menu 3: Beri Nilai & Catatan"
echo "   - Pilih laporan dari mhs1, input nilai & catatan"
echo ""
echo "4. Login sebagai mhs1 (Mahasiswa)"
echo "   - Pilih Menu 3: Lihat Status & Nilai Laporan"
echo "   - Lihat nilai + catatan dari asisten1"
echo ""
echo "========================================"
echo "Jalankan aplikasi:"
echo ""
echo "cd /home/potydev/tugas/Tugas-1-PBO-DapotMatthewTampubolon"
echo "java -cp \"bin:lib/*\" Main"
echo ""
echo "========================================"
